### ISSUE TITLE
wireguard_start.bat gives "The system cannot find the path specified."

### ISSUE THREAD

**Issue by annaparker** [Infini7y77/wireguard-server-on-mswin#1]
Hello! Win8.1 x64, wireguard v0.1.0, Administrator account, UAC disabled, firewall disabled, powershell works, wg0_server.conf edited. Imported .conf file to wireguard gui starts successfully. Time to wireguard_start.bat which doesn't start wireguard and other things.

```
C:\wireguard>wireguard_start.bat
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
#*# wireguard_start --- Done ---
```

**Comment by Infini7y77** [comment]
Please check you copied all the files to the service directory (in the default case C:\wireguard)
You can edit the wireguard_start.bat and put an "echo %_logfile%" or "echo %<variable_name>%" after a SET and verify the file variables are pointing to a valid file location.

The 7 fails of "The system cannot find the path specified." suggest its the logfile path.  The issue there could be the %DATE% included in the logfile filename and if you use a system date format with "/".  You can modify the line: 
`SET _logfile=%_service_dir%\%_service_name%_service_%DATE%.log` 
and remove the "%DATE%" from the filename (or update your system date format to YYYY-MM-DD or the like).

**Comment by annaparker** [comment]
Yup, the %DATE% was the problem. Removed it from .bat files and it starts. Client is able to connect, but there's no routing of server's internet connection. Thank you for the great scripts.

**Comment by Infini7y77** [comment]
Good to hear, Thanks.

Routing is a whole other ball of rubber-bands.  So I will call this issue closed ;).
